sudo: required
dist: trusty
language: java
jdk:
  - oraclejdk8

compiler:
    - gcc
    - clang

env:
  global:
      - AMDAPPSDKROOT=${HOME}/AMDAPPSDK

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - opencl-headers

cache:
    directories:
        - ${AMDAPPSDKROOT}

before_install:
    - sudo apt-get update
    - sudo apt-get install fglrx opencl-headers
    - . .travis/install_amd_sdk.sh;
